name: CD

on:
  push:
    branches:
      - main

env:
  V_BYPASS_ENV_CHECK: 1

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        node: [22]
        pnpm: [9]
        experimental: [false]

    name: 🚀 V Vite CD on Node-${{ matrix.node }} with ${{ matrix.pnpm }} under ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm }}

      - name: Install Dependencies
        run: make install

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
