name: CI

on: ['push', 'pull_request']

env:
  V_BYPASS_ENV_CHECK: 1

jobs:
  monorepo:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        experimental: [false]
        runtime: [node, deno, bun]
    name: 👷 V Vite Monorepo ${{ matrix.pm }} on ${{ matrix.runtime }} under ${{ matrix.os }}

    timeout-minutes: 60

    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v4

      - name: Setup Test Environment
        uses: siguici/setup-js@v1
        with:
          rutime: ${{ matrix.runtime }}
          scripts: build,test
